### ISSUE TITLE
Document how to run this in production

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark-playground#5]
Flask screams that it is not a production webserver whenever it starts up.  I think this is now useful enough to actually put in use.  I have provisioned an Ubuntu VM and now we need figure out how to run it.

I assume we'll use something like nginx or lighttpd in front and forward to... what?  I don't have any familiarity with deploying WSGI applications.

Also, I am wondering whether it might be a good idea to run the entire thing in a Docker container.  Not so much to package the dependencies, which are not very complicated, but to sandbox it from other things running on the system.

**Comment by kfl** [comment]
I'd suggest to hide your flask webserver (perhaps in a docker) behind nginx, and let nginx take care of https (via Let's Encrypt) and so on.

See for instance <https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-gunicorn-and-nginx-on-ubuntu-22-04> for a tutorial. Or <https://github.com/docker/awesome-compose/tree/master/nginx-wsgi-flask> for the same thing dockerized (and with less details).

**Comment by athas** [comment]
Yes, that sounds like the right approach.
